language: r
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - ./install_beast2

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'

after_failure:
  - cat /home/travis/build/richelbilderbeek/beastier/..Rcheck/00install.out
  - cat /home/travis/build/richelbilderbeek/beastier/..Rcheck/00check.log
