language: r
cache: packages
sudo: false

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/beautier
  - richelbilderbeek/tracerer

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "source(\"R/install_beast2.R\"); install_beast2()"
  #- ./install_beast2
  # proselint
  - sudo pip install proselint
  # markdown-link-check, temporarily disabled due to CERT_UNTRUSTED
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  # temporarily disabled due to CERT_UNTRUSTED
  #- ./check_dead_links

after_failure:
  - cat /home/travis/build/richelbilderbeek/beastier/..Rcheck/00install.out
  - cat /home/travis/build/richelbilderbeek/beastier/..Rcheck/00check.log
