language: r

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx

cache: packages

r_packages:
  - devtools
  - hunspell

r_binary_packages:
  - phangorn

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # BEAST2
  - Rscript -e "source(\"R/install_beast2.R\"); source(\"R/get_default_beast2_download_url.R\"); source(\"R/check_os.R\"); install_beast2()"
  # proselint
  - sudo pip install proselint
  # markdown-link-check, temporarily disabled due to CERT_UNTRUSTED
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi
  - # Build for CRAN
  - cd scripts; ./build_cran
  # temporarily disabled due to CERT_UNTRUSTED
  #- ./check_dead_links

after_failure:
  - cat /home/travis/build/ropensci/beastier/..Rcheck/00install.out
  - cat /home/travis/build/ropensci/beastier/..Rcheck/00check.log
